import Head from 'next/head'
import { Inter, Splash } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { SignUp, SignIn, useAuth } from "@clerk/nextjs";
import { useRouter } from 'next/router';

export default function SignUpPage() {
    return <>
        <Head>
          <title>BookTok Project 2</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        
        <main className={styles.main}>

            <div class="columns is-multiline is-centered is-narrow">
                <div class="column is-one-quarter">
                    <img src = '/SplashPage.jpeg' class={styles.landingImage}></img> 
                </div>

                <div class="column">
                    <h1 className={styles.title}>Welcome to YumYumTok!</h1>
                    <p className={styles.landingDescription}>An application to keep track of your visits to restaurants!</p>
                    
                    <div class="columns is-centered">
                        <div class="column is-half">
                            <SignUp path="/signup" routing="path" signInUrl="/" redirectUrl='/home'/>
                        </div>
                    </div>
                </div>
            </div>

        </main>

        
      </>
}
  
    // return<>
    //     <h1>Sign Up</h1>
    //     <SignUp path="/signup" routing="path" signInUrl="/" redirectUrl='/home'/>
    // </>
